# Generated by Django 4.0.2 on 2022-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postpicture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
