# Generated by Django 4.0.2 on 2022-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpicture',
            field=models.ImageField(upload_to='blogApp/static/img/'),
        ),
    ]
