# Generated by Django 4.0.2 on 2022-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_remove_post_postpicture_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postpicture',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blogApp.Tag'),
        ),
    ]
