# Generated by Django 4.0.2 on 2022-02-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_post_postpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postpicture',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
