# Generated by Django 4.0.2 on 2022-02-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
    ]
